use_frameworks!

platform :ios, '8.0'

target 'FaceSDKForQNJ_Example' do
  pod 'FaceSDKForQNJ', :path => '../'

  target 'FaceSDKForQNJ_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
